# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Sebha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AADraggableView'
  # Pods for Sebha

  target 'SebhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SebhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
